name: Tupson

gh:
  handle: "sake92"
  projectName: "tupson"
  url: "https://github.com/sake92/tupson"
  sourcesUrl: "https://github.com/sake92/tupson/tree/main"

artifact:
  org: "ba.sake"
  name: "tupson"
  version: "0.14.0"

config_artifact:
  org: "ba.sake"
  name: "tupson-config"
  version: "0.14.0"
